// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RequestCompleted.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "RequestCompleted.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace rc {

namespace {

const ::google::protobuf::Descriptor* RequestCompleted_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  RequestCompleted_reflection_ = NULL;
const ::google::protobuf::EnumDescriptor* RequestCompleted_MessageID_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_RequestCompleted_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AssignDesc_RequestCompleted_2eproto() {
  protobuf_AddDesc_RequestCompleted_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "RequestCompleted.proto");
  GOOGLE_CHECK(file != NULL);
  RequestCompleted_descriptor_ = file->message_type(0);
  static const int RequestCompleted_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RequestCompleted, transferid_),
  };
  RequestCompleted_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      RequestCompleted_descriptor_,
      RequestCompleted::default_instance_,
      RequestCompleted_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RequestCompleted, _has_bits_[0]),
      -1,
      -1,
      sizeof(RequestCompleted),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RequestCompleted, _internal_metadata_),
      -1);
  RequestCompleted_MessageID_descriptor_ = RequestCompleted_descriptor_->enum_type(0);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_RequestCompleted_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      RequestCompleted_descriptor_, &RequestCompleted::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_RequestCompleted_2eproto() {
  delete RequestCompleted::default_instance_;
  delete RequestCompleted_reflection_;
}

void protobuf_AddDesc_RequestCompleted_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AddDesc_RequestCompleted_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\026RequestCompleted.proto\022\002rc\";\n\020RequestC"
    "ompleted\022\022\n\ntransferID\030\001 \002(\r\"\023\n\tMessageI"
    "D\022\006\n\002ID\020\005", 89);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "RequestCompleted.proto", &protobuf_RegisterTypes);
  RequestCompleted::default_instance_ = new RequestCompleted();
  RequestCompleted::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_RequestCompleted_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_RequestCompleted_2eproto {
  StaticDescriptorInitializer_RequestCompleted_2eproto() {
    protobuf_AddDesc_RequestCompleted_2eproto();
  }
} static_descriptor_initializer_RequestCompleted_2eproto_;

// ===================================================================

const ::google::protobuf::EnumDescriptor* RequestCompleted_MessageID_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return RequestCompleted_MessageID_descriptor_;
}
bool RequestCompleted_MessageID_IsValid(int value) {
  switch(value) {
    case 5:
      return true;
    default:
      return false;
  }
}

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const RequestCompleted_MessageID RequestCompleted::ID;
const RequestCompleted_MessageID RequestCompleted::MessageID_MIN;
const RequestCompleted_MessageID RequestCompleted::MessageID_MAX;
const int RequestCompleted::MessageID_ARRAYSIZE;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int RequestCompleted::kTransferIDFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

RequestCompleted::RequestCompleted()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:rc.RequestCompleted)
}

void RequestCompleted::InitAsDefaultInstance() {
}

RequestCompleted::RequestCompleted(const RequestCompleted& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:rc.RequestCompleted)
}

void RequestCompleted::SharedCtor() {
  _cached_size_ = 0;
  transferid_ = 0u;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

RequestCompleted::~RequestCompleted() {
  // @@protoc_insertion_point(destructor:rc.RequestCompleted)
  SharedDtor();
}

void RequestCompleted::SharedDtor() {
  if (this != default_instance_) {
  }
}

void RequestCompleted::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* RequestCompleted::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return RequestCompleted_descriptor_;
}

const RequestCompleted& RequestCompleted::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_RequestCompleted_2eproto();
  return *default_instance_;
}

RequestCompleted* RequestCompleted::default_instance_ = NULL;

RequestCompleted* RequestCompleted::New(::google::protobuf::Arena* arena) const {
  RequestCompleted* n = new RequestCompleted;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void RequestCompleted::Clear() {
// @@protoc_insertion_point(message_clear_start:rc.RequestCompleted)
  transferid_ = 0u;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  if (_internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->Clear();
  }
}

bool RequestCompleted::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:rc.RequestCompleted)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required uint32 transferID = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &transferid_)));
          set_has_transferid();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:rc.RequestCompleted)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:rc.RequestCompleted)
  return false;
#undef DO_
}

void RequestCompleted::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:rc.RequestCompleted)
  // required uint32 transferID = 1;
  if (has_transferid()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->transferid(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:rc.RequestCompleted)
}

::google::protobuf::uint8* RequestCompleted::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:rc.RequestCompleted)
  // required uint32 transferID = 1;
  if (has_transferid()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->transferid(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:rc.RequestCompleted)
  return target;
}

int RequestCompleted::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:rc.RequestCompleted)
  int total_size = 0;

  // required uint32 transferID = 1;
  if (has_transferid()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->transferid());
  }
  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void RequestCompleted::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:rc.RequestCompleted)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const RequestCompleted* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const RequestCompleted>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:rc.RequestCompleted)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:rc.RequestCompleted)
    MergeFrom(*source);
  }
}

void RequestCompleted::MergeFrom(const RequestCompleted& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:rc.RequestCompleted)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_transferid()) {
      set_transferid(from.transferid());
    }
  }
  if (from._internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->MergeFrom(from.unknown_fields());
  }
}

void RequestCompleted::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:rc.RequestCompleted)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void RequestCompleted::CopyFrom(const RequestCompleted& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:rc.RequestCompleted)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool RequestCompleted::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  return true;
}

void RequestCompleted::Swap(RequestCompleted* other) {
  if (other == this) return;
  InternalSwap(other);
}
void RequestCompleted::InternalSwap(RequestCompleted* other) {
  std::swap(transferid_, other->transferid_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata RequestCompleted::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = RequestCompleted_descriptor_;
  metadata.reflection = RequestCompleted_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// RequestCompleted

// required uint32 transferID = 1;
bool RequestCompleted::has_transferid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void RequestCompleted::set_has_transferid() {
  _has_bits_[0] |= 0x00000001u;
}
void RequestCompleted::clear_has_transferid() {
  _has_bits_[0] &= ~0x00000001u;
}
void RequestCompleted::clear_transferid() {
  transferid_ = 0u;
  clear_has_transferid();
}
 ::google::protobuf::uint32 RequestCompleted::transferid() const {
  // @@protoc_insertion_point(field_get:rc.RequestCompleted.transferID)
  return transferid_;
}
 void RequestCompleted::set_transferid(::google::protobuf::uint32 value) {
  set_has_transferid();
  transferid_ = value;
  // @@protoc_insertion_point(field_set:rc.RequestCompleted.transferID)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace rc

// @@protoc_insertion_point(global_scope)
